# Generated by Django 5.1.3 on 2025-05-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0011_alter_athlete_real_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('Athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.athlete')),
                ('invited_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_review_auths', to='Users.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_auths', to='Users.userprofile')),
            ],
        ),
    ]
