# Generated by Django 5.1.3 on 2025-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authrequest',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
