# Generated by Django 5.1.3 on 2025-05-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_authrequest_reject_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authrequest',
            old_name='applied_at',
            new_name='replied_at',
        ),
    ]
