# Generated by Django 5.1.3 on 2025-05-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_rename_applied_at_authrequest_replied_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authrequest',
            old_name='sent_at',
            new_name='applied_at',
        ),
    ]
