# Generated by Django 5.1.3 on 2025-04-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('real_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='真实姓名')),
                ('org', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属团体')),
                ('Is_Department_Official', models.BooleanField(default=False, verbose_name='是否体干')),
                ('Is_Contest_Official', models.BooleanField(default=False, verbose_name='是否比赛官员')),
                ('Is_System_Admin', models.BooleanField(default=False, verbose_name='是否系统管理员')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['create_time'],
            },
        ),
    ]
