# Generated by Django 5.1.3 on 2025-04-09 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Is_Contest_Official',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_Is_Contest_Official',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None, verbose_name='可管比赛列表'),
        ),
    ]
