# Generated by Django 5.1.3 on 2025-04-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_userprofile_is_contest_official_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='new_Is_Contest_Official',
            new_name='Is_Contest_Official',
        ),
    ]
