# Generated by Django 5.1.3 on 2025-04-26 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_new_is_contest_official_userprofile_is_contest_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('org', models.CharField(max_length=50, verbose_name='所属团体')),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athelete_user', to='Users.userprofile', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to='Users.athlete', verbose_name='运动员')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Users.userprofile', verbose_name='用户')),
            ],
        ),
    ]
