# Generated by Django 5.1.3 on 2025-05-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_athlete_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='org',
        ),
    ]
