# Generated by Django 5.1.3 on 2025-05-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_athlete_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='real_name',
            field=models.CharField(max_length=30, verbose_name='真实姓名'),
        ),
    ]
