# Generated by Django 5.1.3 on 2025-05-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_athlete_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athelete_user', to='Users.userprofile', verbose_name='用户'),
        ),
    ]
