# Generated by Django 5.1.6 on 2025-05-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0012_alter_athlete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="User",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="athlete_user",
                to="Users.userprofile",
                verbose_name="用户",
            ),
        ),
    ]
