# Generated by Django 5.1.6 on 2025-05-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0013_alter_athlete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="real_name",
        ),
    ]
