image: registry.spring25a.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - main
    - dev

unit-test:
  image: python:3.11
  stage: test
  variables:
    DEPLOY: "1"
  before_script:
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
  script:
    - python manage.py makemigrations
    - python manage.py migrate
    - bash test.sh
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://api.spring25a.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
    - sed -i 's/sonarqube.secoder.net/sonarqube.spring25a.secoder.net/g' /opt/sonar-scanner/conf/sonar-scanner.properties
    - sed -i 's/api.secoder.net/api.spring25a.secoder.net/g' /opt/sonar-scanner/bin/sonar-scanner
    - /opt/sonar-scanner/bin/sonar-scanner
  allow_failure: true

deploy:
  stage: deploy
  script:
    - export API_SERVER=https://deployer.spring25a.secoder.net/api
    - deployer dyno replace "$CI_PROJECT_NAME" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - main

dev-deploy:
  stage: deploy
  script:    
    - export API_SERVER=https://deployer.spring25a.secoder.net/api    
    - deployer dyno replace "dev-backend" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"  
  only:    
    - dev
