# Generated by Django 5.1.6 on 2025-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='leixing',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='xingbie',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='zubie',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('contest', 'name', 'leixing', 'zubie', 'xingbie')},
        ),
    ]
